version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
      - npm install -g aws-cdk
  build:
    commands:
      - cdk synth
artifacts:
  base-directory: cdk.out
  files:
    - '**/*'
